### ISSUE TITLE
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long 	at com.kazurayam.inspectus.materialize.selenium.WebPageMaterializingFunctions.lambda$new$1(WebPageMaterializingFunctions.java:77)

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/inspectus#71]
On Windows 10, I got an error

```
Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long
	at com.kazurayam.inspectus.materialize.selenium.WebPageMaterializingFunctions.lambda$new$1(WebPageMaterializingFunctions.java:77)
	at com.kazurayam.inspectus.materialize.selenium.WebPageMaterializingFunction$accept.call(Unknown Source)
	at materialize.takeScreenshot(materialize:21)
	at Script1667709728945$takeScreenshot.callCurrent(Unknown Source)
	at materialize.run(materialize:50)
```

**Comment by kazurayam** [comment]
0.14.2, WebPageMaterialzingFunctions.java:77
```
float dpr = (long)js.executeScript("return window.devicePixelRatio;") * 1.0f;
```

**Comment by kazurayam** [comment]
The currnet code compiles and runs OK on my Mac book air.
on my Mac DPR is possiblly 2.0


The current code failed on my Windows 10 Note book of Mouse.
i do not know th value of DPR on this device, but possibly is not 2. It would be some floating point value, so an Exception raised.

**Comment by kazurayam** [comment]
On Windows PC, I ran MyAdmin test, and got
```
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Double
	at com.kazurayam.inspectus.materialize.selenium.WebPageMaterializingFunctions.lambda$new$1(WebPageMaterializingFunctions.java:77)
	at com.kazurayam.inspectus.materialize.selenium.WebPageMaterializingFunction$accept.call(Unknown Source)
	at Script1668563538525$_run_closure1.doCall(Script1668563538525.groovy:28)
	at processTargetList.run(processTargetList:20)
        ...
```

This time, it seems that the code `js.executeScript("return window.devicePixelRatio;")` returned Long, not Double.

In other words, on Windows, the code   `js.executeScript("return window.devicePixelRatio;")` sometimes returns Double, and sometimes returns Long. Undetermined behavior.

How to manage this?
